# Data en preprocessing

De volgende code is gebruikt om de datasets op te schonen, te filteren en samen te voegen.

In [ ]:
import pandas as pd
# Stap 1: Laad de datasets 

df1 = pd.read_csv("data.csv") # Rajeevw (prestaties en fysieke data) 

df2 = pd.read_csv("ufc-master.csv") # Mdabbert (aanvullende info) 

 

# Stap 2: Harmoniseer kolomnamen in df2 

df2 = df2.rename(columns={ 

'RedFighter': 'R_fighter', 

'BlueFighter': 'B_fighter' 

}) 

 

# Stap 3: Merge datasets op vechtersnamen (datum wordt genegeerd) 

df_merged = pd.merge(df1, df2, on=['R_fighter', 'B_fighter'], how='inner') 

 

# Stap 4: Selecteer relevante kolommen 

relevant_columns = [ 

'R_age', 'B_age', 

'R_Height_cms', 'B_Height_cms', 

'R_Reach_cms', 'B_Reach_cms', 

'R_avg_SIG_STR_pct', 'B_avg_SIG_STR_pct', 

'R_avg_TD_pct', 'B_avg_TD_pct', 

'R_avg_SUB_ATT', 'B_avg_SUB_ATT', 

'weight_class', 

'Winner_x' 

] 

df_clean = df_merged[relevant_columns].copy() 

 

# Stap 5: Verwijder onbekende waarden 

df_clean = df_clean.replace(['Unknown', 'Unclear', 'unk', 'UNK', '?'], pd.NA) 

 

# Stap 6: Verwijder rijen met ontbrekende waarden 

df_clean = df_clean.dropna() 

 

# Stap 7: Verwijder catchweight- én vrouwelijke gewichtsklassen 

df_clean = df_clean[~df_clean['weight_class'].str.contains('Catch|Women', case=False, na=False)] 

 

# Stap 8: Hernoem 'Winner_x' naar 'Winner' 

df_clean = df_clean.rename(columns={'Winner_x': 'Winner'}) 

df_clean = df_clean.reset_index(drop=True)

# Stap 9: Voeg verschilvariabelen toe 

df_clean['age_diff'] = df_clean['R_age'] - df_clean['B_age'] 

df_clean['height_diff'] = df_clean['R_Height_cms'] - df_clean['B_Height_cms'] 

df_clean['reach_diff'] = df_clean['R_Reach_cms'] - df_clean['B_Reach_cms'] 

df_clean['strike_acc_diff'] = df_clean['R_avg_SIG_STR_pct'] - df_clean['B_avg_SIG_STR_pct'] 

df_clean['td_acc_diff'] = df_clean['R_avg_TD_pct'] - df_clean['B_avg_TD_pct'] 

df_clean['sub_att_diff'] = df_clean['R_avg_SUB_ATT'] - df_clean['B_avg_SUB_ATT'] 

 

# Stap 10: Opslaan als nieuwe CSV 

df_clean.to_csv("ufc_clean.csv", index=False) 

 

# Stap 11: Eerste 5 rijen laten zien 

print(df_clean.head(5))

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3